"""empty message

Revision ID: 0b76d9e7a3d1
Revises: a40a7c6a06b5
Create Date: 2020-04-12 22:50:06.863691

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b76d9e7a3d1'
down_revision = 'a40a7c6a06b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_role_menu',
    sa.Column('rid', sa.Integer(), nullable=True),
    sa.Column('mid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['mid'], ['t_menu.id'], ),
    sa.ForeignKeyConstraint(['rid'], ['t_role.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_role_menu')
    # ### end Alembic commands ###
