"""empty message

Revision ID: 2da8744f9089
Revises: 45a87ef4dce0
Create Date: 2020-04-26 19:10:31.777506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2da8744f9089'
down_revision = '45a87ef4dce0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goods', sa.Column('is_promote', sa.Integer(), nullable=True))
    op.drop_column('t_goods', 'is_promte')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_goods', sa.Column('is_promte', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('t_goods', 'is_promote')
    # ### end Alembic commands ###
