"""empty message

Revision ID: 965e7b1ea9b4
Revises: 0b76d9e7a3d1
Create Date: 2020-04-18 18:13:41.406621

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '965e7b1ea9b4'
down_revision = '0b76d9e7a3d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('t_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.Column('pid', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['pid'], ['t_category.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('t_category')
    # ### end Alembic commands ###
