"""empty message

Revision ID: a40a7c6a06b5
Revises: f8646e6d20eb
Create Date: 2020-04-12 14:54:35.615358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a40a7c6a06b5'
down_revision = 'f8646e6d20eb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_user', sa.Column('rid', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 't_user', 't_role', ['rid'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 't_user', type_='foreignkey')
    op.drop_column('t_user', 'rid')
    # ### end Alembic commands ###
