"""empty message

Revision ID: aa767a9c7483
Revises: 
Create Date: 2020-04-12 01:24:41.330409

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'aa767a9c7483'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 't_menu', 't_menu', ['pid'], ['id'])
    op.drop_column('t_menu', 'name2')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('t_menu', sa.Column('name2', mysql.VARCHAR(length=32), nullable=False))
    op.drop_constraint(None, 't_menu', type_='foreignkey')
    # ### end Alembic commands ###
